---
variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - lint

gitleaks:
  tags:
    - secret-scanning
  stage: lint
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.24.0-mega
    entrypoint: [""]
  script:
    - git fetch origin $CI_DEFAULT_BRANCH:$CI_DEFAULT_BRANCH
    - gitleaks git --verbose --redact -c .gitleaks/gitleaks.toml --log-opts="$CI_DEFAULT_BRANCH..$CI_COMMIT_SHA"

wait_for_jenkins:
  stage: lint
  script:
    - echo "Waiting for Jenkins..." # Wait for mr-head job in Jekins
    - sleep 500